config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  scope '(:locale)', locale: /es|en/ do
    devise_for :users, controllers: { registrations: 'users/registrations' }
    resources :vehicles do
      put :enable
      put :disable
      resources :legal_documents, except: :destroy
      resources :reservations
    end
    resources :reservations, only: :index do
      resources :payments, except: :destroy
    end
    resources :users, except: :destroy do
      resources :legal_documents, except: :destroy
      resources :driver_accounts, path: :driver, except: %i[destroy index]
    end
    resources :driver_accounts, path: :driver, only: :index do
      resources :legal_documents, except: :destroy
    end
    resources :vehicle_models, except: :destroy
    resources :fees, except: :destroy
    resources :brands, except: :destroy
    delete '/images/(:id)', to: 'images#destroy', as: :destroy_images
    get 'search/index', to: 'search#index'
    get 'my_reservations', to: 'my_reservations#index'
    get '/my_vehicles', to: 'my_vehicles#index'
    get '/validate_legal_documents', to: 'validate_legal_documents#index'
    get '/welcome', to: 'welcome#index'
    get 'my_vehicles_reservations', to: 'my_vehicles_reservations#index'
    root to: 'welcome#index'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

# WelcomeController
class WelcomeController < ApplicationController
  def index
  end
end

app/views/welcome/index.html.erb
  <h3 class="card-header">Bienvenido <%= current_user.first_name %>!</h3>
  <div class="card-deck mt-5 ml-3 mr-3">
    <div class='col-md-4 card shadow'>
      <h5 class="card-title">Identificación general  
        <img src="https://img.icons8.com/doodle/48/000000/information.png">
      </h5>
      <p class="card-text underline-bold">Todo usuario debe cumplir los siguientes requisitos:</p>
        <li>Ser mayor de 27 años.</li>
        <li>Adjuntar Cedula de identidad <%= link_to 'Aquí', user_legal_documents_path(current_user), target: '_blank' %></li>
        <li>Adjuntar Certificado de antecedentes <%= link_to 'Aquí', user_legal_documents_path(current_user), target: '_blank' %></li>
        <li>Espera a que validemos tus documentos, se te notificará mediante un Email.</li>
        <br>
    </div>
    <div class='col-md-4 card shadow'>
      <h5 class="card-title">¿ Deseas conducír un Vehículo ?
        <img src="https://img.icons8.com/color/48/000000/car.png">
      </h5>
      <p class="card-text underline-bold">Requisitos:</p>
        <li>Debes crear una cuenta de Conductor <%= link_to 'Aquí', new_user_driver_account_path(current_user), target: '_blank'  %></li>
        <br>
      <p class="card-text underline-bold">Una vez creada tu cuenta debes cumplir con lo siguiente:</p>
        <li>Adjuntar Licencia de conducir vigente 
          <%= link_to 'Aquí', driver_account_legal_documents_path(current_user.driver_account),
              target: '_blank' if current_user.driver_account %>
        </li>
        <li>Adjuntar Hoja de vida de conductor 
            <%= link_to 'Aquí', driver_account_legal_documents_path(current_user.driver_account),
                target: '_blank' if current_user.driver_account %>
        </li>
        <br>
    </div>
    <div class='col-md-4 card shadow'> 
      <h5 class="card-title">¿ Deseas publicar un Vehículo ? 
        <img src="https://img.icons8.com/doodle/48/000000/money.png">
      </h5>
      <li class="card-text">Puedes crear tus vehículos 
        <%= link_to 'aquí', new_vehicle_path,
            target: '_blank' if current_user %>
      </li>
      <br>
      <p class="card-text underline-bold">Para cada vehículo se debe adjuntar la siguiente documentación:</p>
        <li>Permiso de circulación vigente.</li>
    </div>
</div>