config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  scope '(:locale)', locale: /es|en/ do
    devise_for :users, controllers: { registrations: 'users/registrations' }
    resources :vehicles do
      put :enable
      put :disable
      resources :legal_documents, except: :destroy
      resources :reservations
    end
    resources :reservations, only: :index do
      resources :payments, except: :destroy
    end
    resources :users, except: :destroy do
      resources :legal_documents, except: :destroy
      resources :driver_accounts, path: :driver, except: %i[destroy index]
    end
    resources :driver_accounts, path: :driver, only: :index do
      resources :legal_documents, except: :destroy
    end
    resources :vehicle_models, except: :destroy
    resources :fees, except: :destroy
    resources :brands, except: :destroy
    delete '/images/(:id)', to: 'images#destroy', as: :destroy_images
    get 'search/index', to: 'search#index'
    get 'my_reservations', to: 'my_reservations#index'
    get '/my_vehicles', to: 'my_vehicles#index'
    get '/validate_legal_documents', to: 'validate_legal_documents#index'
    get '/welcome', to: 'welcome#index'
    get 'my_vehicles_reservations', to: 'my_vehicles_reservations#index'
    root to: 'welcome#index'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/fee.rb
class Fee < ApplicationRecord
  validates_presence_of %i[amount engine_type body_type]
end

app/controllers/fees_controller.rb
class FeesController < ApplicationController
  load_and_authorize_resource
  before_action :set_fee, only: [:show, :edit, :update, :destroy]

  # GET /fees
  # GET /fees.json
  def index
    @fees = Fee.all
  end

  # GET /fees/1
  # GET /fees/1.json
  def show
  end

  # GET /fees/new
  def new
    @fee = Fee.new
  end

  # GET /fees/1/edit
  def edit
  end

  # POST /fees
  # POST /fees.json
  def create
    @fee = Fee.new(fee_params)

    respond_to do |format|
      if @fee.save
        format.html { redirect_to @fee, notice: 'Fee was successfully created.' }
        format.json { render :show, status: :created, location: @fee }
      else
        format.html { render :new }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fees/1
  # PATCH/PUT /fees/1.json
  def update
    respond_to do |format|
      if @fee.update(fee_params)
        format.html { redirect_to @fee, notice: 'Fee was successfully updated.' }
        format.json { render :show, status: :ok, location: @fee }
      else
        format.html { render :edit }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fees/1
  # DELETE /fees/1.json
  def destroy
    @fee.destroy
    respond_to do |format|
      format.html { redirect_to fees_url, notice: 'Fee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fee
      @fee = Fee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fee_params
      params.require(:fee).permit(:engine_type, :body_type, :amount)
    end
end

app/views/fees/_form.html.erb
<%= form_with(model: fee, local: true) do |form| %>
  <% if fee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fee.errors.count, "error") %> prohibited this fee from being saved:</h2>

      <ul>
        <% fee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :engine_type %>
    <%= form.text_field :engine_type %>
  </div>

  <div class="field">
    <%= form.label :body_type %>
    <%= form.text_field :body_type %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fees/edit.html.erb
<h1>Editing Fee</h1>

<%= render 'form', fee: @fee %>

<%= link_to 'Show', @fee %> |
<%= link_to 'Back', fees_path %>

app/views/fees/index.html.erb
<h1>Fees</h1>

<table>
  <thead>
    <tr>
      <th>Engine type</th>
      <th>Body type</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fees.each do |fee| %>
      <tr>
        <td><%= fee.engine_type %></td>
        <td><%= fee.body_type %></td>
        <td><%= fee.amount %></td>
        <td><%= link_to 'Show', fee %></td>
        <td><%= link_to 'Edit', edit_fee_path(fee) %></td>
        <td><%= link_to 'Destroy', fee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fee', new_fee_path %>

app/views/fees/new.html.erb
<h1>New Fee</h1>

<%= render 'form', fee: @fee %>

<%= link_to 'Back', fees_path %>

app/views/fees/show.html.erb
<p>
  <strong>Engine type:</strong>
  <%= @fee.engine_type %>
</p>

<p>
  <strong>Body type:</strong>
  <%= @fee.body_type %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @fee.amount %>
</p>

<%= link_to 'Edit', edit_fee_path(@fee) %> |
<%= link_to 'Back', fees_path %>