config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  scope '(:locale)', locale: /es|en/ do
    devise_for :users, controllers: { registrations: 'users/registrations' }
    resources :vehicles do
      put :enable
      put :disable
      resources :legal_documents, except: :destroy
      resources :reservations
    end
    resources :reservations, only: :index do
      resources :payments, except: :destroy
    end
    resources :users, except: :destroy do
      resources :legal_documents, except: :destroy
      resources :driver_accounts, path: :driver, except: %i[destroy index]
    end
    resources :driver_accounts, path: :driver, only: :index do
      resources :legal_documents, except: :destroy
    end
    resources :vehicle_models, except: :destroy
    resources :fees, except: :destroy
    resources :brands, except: :destroy
    delete '/images/(:id)', to: 'images#destroy', as: :destroy_images
    get 'search/index', to: 'search#index'
    get 'my_reservations', to: 'my_reservations#index'
    get '/my_vehicles', to: 'my_vehicles#index'
    get '/validate_legal_documents', to: 'validate_legal_documents#index'
    get '/welcome', to: 'welcome#index'
    get 'my_vehicles_reservations', to: 'my_vehicles_reservations#index'
    root to: 'welcome#index'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vehicle.rb
# frozen_string_literal: true

# Vehicle
class Vehicle < ApplicationRecord
  acts_as_paranoid
  include Documentable
  belongs_to :vehicle_model
  belongs_to :user
  belongs_to :fee, required: false
  has_many :reservations, dependent: :destroy
  has_many_attached :images

  ATTACHMENTS_LIMIT = 5
  REQUIRED_DOCUMENTS = %w[circulation_permit].freeze
  ALLOWED_FILE_TYPES = ['image/png', 'image/jpg', 'image/jpeg'].freeze
  STATUSES_TABLE_COLORS = {
    created: :info,
    review: :danger,
    ready: :success,
    published: :success,
    rented: :info,
    disabled: :warning
  }.freeze

  # ====================
  # =     ENUMS        =
  # ====================
  enum body_type: %i[citycar sedan]
  enum engine_type: %i[gasoline diesel]
  enum transmission: %i[manual automatic]
  enum steering: %i[mechanical power electric hydraulic]
  enum drive: %w[4x2 4x4]
  enum status: %i[created review ready published rented disabled temp_disabled]
  translate_enum :body_type
  translate_enum :engine_type
  translate_enum :transmission
  translate_enum :steering
  translate_enum :status

  # ====================
  # =   VALIDATORS     =
  # ====================
  validates_presence_of %i[year license_plate engine_number
                           chasis_number]
  validates :year, length: { is: 4 }
  validates :license_plate, length: { is: 6 }
  validates :odometer, length: { in: 1..7 }
  validates_length_of :images, maximum: ATTACHMENTS_LIMIT
  validates :images, presence: true, on: :create
  validates :images, attached: true, content_type: ALLOWED_FILE_TYPES
  validate :active_reservations, on: :update, if: :disabled?

  # ====================
  # =    CALLBACKS     =
  # ====================
  before_create :associate_fee
  before_save :upcase_license_plate

  # ====================
  # =      SCOPES      =
  # ====================
  scope :not_from_current_user, lambda { |current_user|
    where.not(user: current_user)
  }
  scope :available, -> { where(status: %w[published rented]) }

  # ====================
  # = INSTANCE METHODS =
  # ====================

  # return sugested start date to reservation
  def reservation_start_date
    reservations.current_and_future&.first&.end_date || Date.today
  end

  def set_status!
    return ready! if legal_documents_effective? && (review? || status.nil?)

    return review! if created? || status.nil?
  end

  def legal_status_badge
    badge_color = STATUSES_TABLE_COLORS[status.to_sym]
    { text: status, badge_color: badge_color }
  end

  def belongs_to_current_user?(current_user)
    user == current_user
  end

  def brand_and_model
    "#{vehicle_model.brand.name} #{vehicle_model.name}"
  end

  def brand_model_and_year
    "#{vehicle_model.brand.name} #{vehicle_model.name} - #{year}"
  end

  def disable
    if reservations.current_and_future.present? || disabled? || temp_disabled?
      return false
    end

    disabled!
  rescue ActiveRecord::ActiveRecordError
    false
  end

  def back_to_status
    return created! if legal_documents.empty?
    return review! unless legal_documents_effective?
    return published! if temp_disabled?

    ready!
  rescue ActiveRecord::ActiveRecordError
    false
  end

  def temporal_disable(user)
    temp_disabled!
    time_to_create_reservation(user)
  rescue StandardError => e
    puts e
    false
  end

  # ====================
  # =  CLASS METHODS   =
  # ====================
  def self.search(params)
    params.downcase!
    base_query = Vehicle.joins(vehicle_model: :brand)
    base_query.where(vehicle_models: { name: params })
              .or(base_query.where('lower(vehicle_models.name) LIKE ?', "%#{params}"))
              .or(base_query.where('lower(vehicle_models.name) LIKE ?', "#{params}%"))
              .or(base_query.where('lower(vehicle_models.name) LIKE ?', "%#{params}%"))
              .or(base_query.where('lower(brands.name) = ?', params))
              .or(base_query.where('lower(brands.name) LIKE ?', "%#{params}"))
              .or(base_query.where('lower(brands.name) LIKE ?', "#{params}%"))
              .or(base_query.where('lower(brands.name) LIKE ?', "%#{params}%"))
  end
  # ====================
  # =     PRIVATE      =
  # ====================

  private

  def time_to_create_reservation(user)
    ReservationDeadlineWorker
      .perform_in(Reservation::DEADLINE_TO_CREATE, id, user.id)
  end

  def active_reservations
    return true if reservations.current_and_future.empty?

    errors.add(:base, 'No puede desactivar vehículo,
                         ya que posee reservas activas')
    false
  end

  def upcase_license_plate
    self.license_plate = license_plate.upcase
  end

  def associate_fee
    fee = Fee.find_by(body_type: body_type, engine_type: engine_type)
    return errors.add(:fee, 'does not exist for your vehicle') if fee.nil?

    self.fee = fee
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  load_and_authorize_resource
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy, :enable, :disable]
  before_action :set_brands, only: %i[edit new create update]
  before_action :validate_legal_documents, only: %i[new create]
  before_action :brand_select_option, only: %i[edit update]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.available
                       .not_from_current_user(current_user)
                       .eager_load(images_attachments: :blob)
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = current_user.vehicles.new(vehicle_params)
    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'El vehículo ha sido creado exitosamente.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'El vehículo ha sido actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    if @vehicle.reservations.present?
      redirect_to @vehicle, alert: 'Vehículo posee historial de reservas, no se puede eliminar'
      return
    end
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'El vehículo ha sido eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  def enable
    respond_to do |format|
      if @vehicle.back_to_status
        format.js { flash[:notice] = 'Vehículo activado!' }
      else
        format.js { flash[:alert] = 'No fué posible activar tu vehículo' }
      end
    end
  end

  def disable
    respond_to do |format|
      if @vehicle.disable
        format.js { flash[:notice] = 'Vehículo desactivado correctamente' }
      else
        format.js { flash[:alert] = 'No fué posible desactivar tu vehículo, revisa si este posee reservas activas' }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.

  def validate_legal_documents
    return if current_user.legal_documents_effective?

    respond_to do |format|
      format.html { redirect_to user_legal_documents_path(current_user), alert: 'Debes validar tu documentacion legal antes de continuar.' }
      format.json { head :no_content }
    end
  end

  def brand_select_option
    @selected_option = @vehicle&.vehicle_model&.brand&.id
    @disabled = true
  end

  def set_brands
    @brands = Brand.preload(:vehicle_models).order(:name)
  end

  def set_vehicle
    @vehicle = Vehicle.find(params[:id] || params[:vehicle_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def vehicle_params
    params.require(:vehicle).permit(:vehicle_model_id, :year, :odometer,
                                    :license_plate, :engine_number, :drive,
                                    :chasis_number, :transmission, :engine_type,
                                    :passenger_capacity, :air_conditioning,
                                    :airbags_quantity, :door_quantity,
                                    :steering, :body_type, :comment, :status,
                                    images: [])
  end
end

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <%= render 'shared/errors', resource: vehicle %>

  <div class="form-group">
    <%= form.collection_select :brand_id, @brands, :id, :name,
        { include_blank: 'Seleccione Marca', selected: @selected_option },
        { class: 'form-control form-control-sm', disabled: @disabled } %>
  </div>

  <div class="form-group">
    <%= form.grouped_collection_select :vehicle_model_id,
        @brands, :vehicle_models, :name, :id, :name,
        { include_blank: 'Seleccione Modelo' }, { class:"form-control form-control-sm" } %>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.select :year, (Date.today.year - 10..Date.today.year + 1),
         { include_blank: 'Año', selected: vehicle.year }, { class:"form-control form-control-sm" } %>
    </div>

    <div class="form-group col-md-6">
      <%= form.text_field :license_plate, class:"form-control form-control-sm",
          placeholder: 'Patente' %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.text_field :engine_number, class:"form-control form-control-sm",
          placeholder: 'Número de motor' %>
    </div>

    <div class="form-group col-md-6">
      <%= form.text_field :chasis_number, class:"form-control form-control-sm",
          placeholder: 'Número de chasís' %>
    </div>
  </div>
  
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.select :body_type, 
          options_for_select(vehicle.class.translated_body_types.map { 
            |t, k, _v| [t, k] 
          }, selected: vehicle.body_type), { include_blank: 'Carrocería' },
          { class:"form-control form-control-sm" } %>
    </div>

    <div class="form-group col-md-6">
      <%= form.select :engine_type,
          options_for_select(vehicle.class.translated_engine_types.map {
            |t, k, _v| [t, k] 
          }, selected: vehicle.engine_type), { include_blank: 'Combustible' },
          { class:"form-control form-control-sm" } %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.number_field :door_quantity, class:"form-control form-control-sm",
          placeholder: 'Cantidad de puertas' %>
    </div>

    <div class="form-group col-md-6">
      <%= form.number_field :passenger_capacity, class:"form-control form-control-sm",
          placeholder: 'Capacidad de pasajeros' %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-1">
      <%= form.check_box :air_conditioning, class:"form-control form-control-sm" %>
      
    </div>
    <div class="form-group col-md-5">
       <%= form.label :air_conditioning, style: "" %>
    </div>
    <div class="form-group col-md-6">
      <%= form.number_field :airbags_quantity, class:"form-control form-control-sm",
          placeholder: 'Cantidad de Airbags' %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.select :transmission,
          options_for_select(vehicle.class.translated_transmissions.map {
            |t, k, _v| [t, k]
          }, selected: vehicle.transmission), { include_blank: 'Transmisión' },
          { class:"form-control form-control-sm" } %>
    </div>

    <div class="form-group col-md-6">
      <%= form.collection_select :drive, Vehicle.drives, :first, :first,
          { include_blank: 'Tracción' },
          { class:"form-control form-control-sm" } %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.select :steering,
          options_for_select(vehicle.class.translated_steerings.map {
            |t, k, _v| [t, k]
          }, selected: vehicle.steering), { include_blank: 'Dirección' },
          { class:"form-control form-control-sm" } %>
    </div>

    <div class="form-group col-md-6">
      <%= form.number_field :odometer, class:"form-control form-control-sm",
          placeholder: 'Kilometraje' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.text_area :comment, class:"form-control form-control-sm",
        placeholder: 'Información adicional' %>
  </div>

  <div class="form-group">
    <div class="input-group">
      <div class="custom-file">
        <%= form.file_field :images, multiple: true, class: "form-control form-control-sm",
            accept: "image/png,image/jpg,image/jpeg", label: "Add an image" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= render 'images', vehicle: vehicle, size:"200x180" %>
  </div>

  <div class="form-group">
    <%= form.submit I18n.t('buttons.submit'), class: "btn btn-outline-primary btn-lg btn-block" %>
  </div>
<% end %>

app/views/vehicles/_index.html.erb
<% resource ||= 'vehicles' %>
<div class="container col-lg-12 col-md-6 col-sm-10">
  <div class="card shadow">
    <h5 class="card-header">
      <%= I18n.t("vehicle.headers.index.#{resource}")%> (<%= @vehicles.count %>)
      <%= link_to '+ Nuevo Vehículo', new_vehicle_path, class:"btn btn-outline-primary", style:'float: right;' %>
    </h5>

    <div class="card-body">
      <div class="row">
        <% @vehicles.each do |vehicle| %>
          <!-- vehicle  -->
          <div class="col-xl-3 col-lg-4 col-md-10 col-sm-12" style="padding-bottom: 20px;">
            <%=link_to vehicle, class:"card-link-hover" do%>
              <div class="card shadow">            
                <div class="inner">
                  <%=image_tag vehicle&.images&.first, size: '300x210', class:"card-img-top" if vehicle.images.present? %>
                </div>
                <div class="card-body mb-0">
                  <p class="card-title bold ml-2"><%= vehicle.brand_model_and_year %></p>
                  <div class="table table-responsive mb-0">
                    <table class="table mb-0">
                      <tbody>
                        <tr>
                          <th style="width:50%"><%= I18n.t('vehicle.show.daily_price') %>:</th>
                          <td><%= number_to_currency(vehicle.fee.amount.to_i)%></td>
                        </tr>          
                        <tr>
                          <th style="width:50%"><%= I18n.t('vehicle.show.fuel') %>:</th>
                          <td><%= Vehicle.translated_engine_type(vehicle.engine_type)  %></td>
                        </tr>
                        <%= render 'vehicles/legal_status', vehicle: vehicle %>
                      </tbody>
                    </table> 
                  </div>
                </div>
              </div>
            <%end%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/vehicles/disable.js.erb
<% if flash[:notice] %>
  toastr.success('<%= flash[:notice] %>')
<% elsif flash[:alert] %>
  toastr.error('<%= flash[:alert] %>')
<% end %>
window.location.reload();

app/views/vehicles/edit.html.erb
<div class="container col-xl-6 col-lg-10 col-md-6 col-sm-10">
  <div class="card">
    <div class="card-header">
      <h2><%=I18n.t('vehicle.headers.edit')%></h2>
    </div>
    <div class="card-body">
      <%= render 'vehicles/partials/form', vehicle: @vehicle %>
      <div class="text-right">
        <%= link_to 'Show', @vehicle %><br>
        <%= link_to 'Back', vehicles_path %>
      </div>
    </div>
  </div>
</div>

app/views/vehicles/enable.js.erb
<% if flash[:notice] %>
  toastr.success('<%= flash[:notice] %>')
<% elsif flash[:alert] %>
  toastr.error('<%= flash[:alert] %>')
<% end %>
window.location.reload();

app/views/vehicles/index.html.erb
<%= render 'vehicles/partials/vehicle_list', vehicles: @vehicles %>

app/views/vehicles/new.html.erb
<div class="container col-xl-7 col-lg-10 col-md-6 col-sm-10">
  <div class="card shadow">
    <div class="card-header">
      <h2 class="text-center"><%=I18n.t('vehicle.headers.new')%></h2>
    </div>
    <div class="card-body"> 
      <%= render 'vehicles/partials/form', vehicle: @vehicle %>
    </div>
  </div>
</div>

app/views/vehicles/show.html.erb
<div class="container col-xl-12 col-lg-10 col-md-6 col-sm-10" id='show_vehicle'>
  <div class="card shadow">
    <div class='row'>
      <div class='col-md-8'>
        <%= render 'vehicles/partials/carousel', vehicle: @vehicle %>
      </div>
      <div class='col-md-4'>
        <div class="card-body">
          <h3 class="card-title"><%= @vehicle.brand_and_model %></h3>
          <!-- upper buttons -->
          <div class='row mb-3' style='float: right;'>
            <%= render 'vehicles/partials/publish_form', vehicle: @vehicle if (@vehicle.ready? || @vehicle.disabled?) && @vehicle.legal_documents_effective? && @vehicle.user == current_user %>
            <%= render 'vehicles/partials/reservation_link', vehicle: @vehicle if @vehicle.published? && !@vehicle.belongs_to_current_user?(current_user) %>
            <div class="btn-group ml-3 mr-3" style='float: right;'>
              <button type="button" class="btn btn-outline-primary dropdown-toggle"
                      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= I18n.t('buttons.options') %>
              </button>
              <!-- OWNER OPTIONS -->
              <div class="dropdown-menu dropdown-menu-right">
                <% if @vehicle.belongs_to_current_user?(current_user) || current_user.admin? %>
                  <%= link_to 'Ver reservas', vehicle_reservations_path(@vehicle), class:"dropdown-item" %>
                  <%= link_to I18n.t('buttons.legal_documents'), vehicle_legal_documents_path(@vehicle), class:"dropdown-item" %>
                  <%= link_to I18n.t('buttons.edit'), edit_vehicle_path(@vehicle), class:"dropdown-item" %>
                  <% if @vehicle.disabled? %>
                    <%= link_to 'Activar',
                        vehicle_enable_path(@vehicle), method: :put,
                        data: { confirm: 'Seguro?' }, action: :enable, remote: true,
                        class:"alert-success dropdown-item" %>
                  <% else %>
                    <%= link_to 'Desactivar',
                        vehicle_disable_path(@vehicle), method: :put, action: :disable, remote: true,
                        class:"alert-warning dropdown-item" %>
                  <% end %>
                  <%= link_to 'Eliminar', @vehicle, method: :delete,
                      class:"alert-danger dropdown-item", data: { confirm: 'Estas seguro?' }%>
                  <div class="dropdown-divider"></div>
                <% end %>
                <!-- OTHER USERS OPTIONS -->
                <%= link_to I18n.t('buttons.back'), vehicles_path, class:"dropdown-item" %>
              </div>
            </div>
          </div>
          <!-- VEHICLE DATA HERE -->
          <%= render 'vehicles/partials/data', vehicle: @vehicle %>
        </div>
      </div>
    </div>  
  </div>
</div>