config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  scope '(:locale)', locale: /es|en/ do
    devise_for :users, controllers: { registrations: 'users/registrations' }
    resources :vehicles do
      put :enable
      put :disable
      resources :legal_documents, except: :destroy
      resources :reservations
    end
    resources :reservations, only: :index do
      resources :payments, except: :destroy
    end
    resources :users, except: :destroy do
      resources :legal_documents, except: :destroy
      resources :driver_accounts, path: :driver, except: %i[destroy index]
    end
    resources :driver_accounts, path: :driver, only: :index do
      resources :legal_documents, except: :destroy
    end
    resources :vehicle_models, except: :destroy
    resources :fees, except: :destroy
    resources :brands, except: :destroy
    delete '/images/(:id)', to: 'images#destroy', as: :destroy_images
    get 'search/index', to: 'search#index'
    get 'my_reservations', to: 'my_reservations#index'
    get '/my_vehicles', to: 'my_vehicles#index'
    get '/validate_legal_documents', to: 'validate_legal_documents#index'
    get '/welcome', to: 'welcome#index'
    get 'my_vehicles_reservations', to: 'my_vehicles_reservations#index'
    root to: 'welcome#index'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/nav/_admin_dropdown.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Admin
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <%= link_to "Marcas", brands_path, class:"dropdown-item" %>
    <%= link_to "Modelos", vehicle_models_path, class:"dropdown-item" %>
    <%= link_to "Usuarios", users_path, class:"dropdown-item" %>
    <%= link_to "Validación documentos", validate_legal_documents_path, class:"dropdown-item" %>
  </div>
</li>

app/views/nav/_main_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top"'>
  <a class="navbar-brand" href="/welcome">Arrienda el Auto</a>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= I18n.t('vehicle.headers.index.vehicles') %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to I18n.t('vehicle.leasing'), vehicles_path, class:"dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to I18n.t('vehicle.headers.index.my_vehicles'), my_vehicles_path, class:"dropdown-item" %>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Reservas
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Reservas realizadas', my_reservations_path, class:"dropdown-item" %>
          <%= link_to 'Reservas de mis vehículos', my_vehicles_reservations_path, class:"dropdown-item" %>
        </div>
      </li>

      <!-- admin menu -->
      <%= render 'nav/admin_dropdown' if current_user&.admin? %>
      <!--  -->
      <%= render 'nav/user_dropdown' if user_signed_in? %>
      <!-- -->
      <li class="nav-item">
        <%if user_signed_in?%>
          <%= link_to I18n.t('devise.text.sign_out'), destroy_user_session_path, method: :delete, class:"nav-link", tabindex:"-1", aria_disabled:"true"  %>
        <%else%>
          <%= link_to I18n.t('devise.text.log_in'), new_user_session_path, class:"nav-link", tabindex:"-1", aria_disabled:"true"  %>
        <%end%>
      </li>
    </ul>          
    <%= render 'nav/search' %>
  </div>
</nav>

app/views/nav/_search.html.erb
<%= form_tag search_index_path, :method => "get", class:"form-inline my-2 my-lg-0" do %>
  <%= text_field_tag :search, params[:search], placeholder: "Buscar", class:"form-control mr-sm-2" %>
  <%= submit_tag "Buscar", class:"btn btn-outline-success my-2 my-sm-0" %>
<% end %>

app/views/nav/_user_dropdown.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= current_user.first_name %>
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <%= link_to "Mi Datos", current_user, class:"dropdown-item" %>
  </div>
</li>